### PR TITLE
Simplify installation of dependencies

### PR DESCRIPTION
**Pull request by joewiz**

### CODE REVIEW

**Comment by donmelton** [comment]
@joewiz Thanks for the patches! I love it when people show interest in the project. However, I don't plan on merging either of these. Let me explain why...

The `brew install` install commands are intentionally listed on separate lines. This is to make it easier for novice command line users to understand what I'm asking them to do. In addition, while it might be faster to install all of the dependencies with a single command, it's harder for a novice to parse the error output if one of those packages fails to install. So, this is one case where being verbose is better.

As far as the other change, the webpage I'm pointing to still titled and described as "Homebrew Cask," not "Caskroom." I'll consider changing the text when they change the project page.

Thanks again.

**Comment by joewiz** [comment]
@donmelton Thank you for your thoughtful reply. I wondered if the individual lines were intentional for that reason. Makes sense. And you're totally right about Homebrew Cask; I hadn't realized that! 

Thanks so much for the great tool (using it right now, earning points with my wife getting her favorite show into Plex), your podcasts with René and Guy, and all of your work before this latest stage of your amazing career!

**Comment by donmelton** [comment]
@joewiz Thanks and you are very welcome, sir!

Keep those patches coming. You never know what I'll take. :)

**Comment by jabooth** [comment]
@donmelton just thought I'd let you know I came to give the same PR just now to simplify the `brew install` down to one line. 

Nice to see your reasoning above, but to play devil's advocate, I'd counter that the unusualness of seeing the four commands separately made me question if there was some sinister reason for it (_maybe `ffmpeg` has to be installed first for some gross install-time dependency resolution reason in the other packages? Would things break if I did these in a different order?_) The instructions as they are gave me the impression things might be more fragile than they actually are.

It's minor, but thought I'd add a data point. :) Now on to try the tools out, thanks!

**Comment by donmelton** [comment]
@jabooth Interesting. Thanks for the feedback!

**Pull request closed without merging**
