### PR TITLE
Add note about install on Win10 linux subsystem

### PR DESCRIPTION
**Pull request by JMoVS**
Add a link to the gist detailing how to install these scripts in Windows 10’s linux subsystem (also for potentially better performance).

### CODE REVIEW

**Comment by JMoVS** [comment]
any thoughts and commendts welcome - I tried to make it as succinct and short as possible, yet still include the link and sort of a warning. My reasoning is that if it's not linked here, nobody will ever really find it. ;-)

**Comment by donmelton** [comment]
@JMoVS Thanks! That looks good. I'll take a closer look later today but I'll probably take this before the next release so it shows up on the GitHub page sooner.

**Comment by JMoVS** [comment]
@donmelton As your next release is seemingly right around the corner, maybe you can include this in conjunction with the result of https://github.com/donmelton/video_transcoding/issues/90

**Comment by donmelton** [comment]
@JMoVS Yes, that's the plan. I'm also trying to get the change for https://github.com/donmelton/video_transcoding/issues/88 into that release.

**Comment by JMoVS** [comment]
wow, you're really fast! Sounds awesome! Big thumbs up from me! 👍

**Comment by samhutchins** [comment]
I spent some time last night going through the gist that's linked in the proposed change, and I was unsuccessful. I got stuck with linuxbrew failing to install pkg-config. I'll try again this evening with a fresher head and see if I can get any further, but that's a conversation for another place

I think it's worth having a note in the readme about using the linux subsystem on Windows but possibly leave figuring out how as an exercise to the reader; similar to how the readme currently just says it's possible to set the scripts up on Windows, but includes no specific steps on how to achieve this

**Comment by JMoVS** [comment]
@samhutchins Hi, I'm the author of said gist. I proposed it there because it give sguidance and figuring this out involved a lot of back and forth on multiple issues on linuxbrew's side. If you could comment on the gist with the error that you encountered, I may be able to help you and update the gist accordingly.

My take so far is: Without this gist, nobody will seriously even manage to do it unless you're doing it as a pet project investing multiple hours. Also, I don't see how it hurts having it there.

So I'm looking forward to hearing from you about the issue and then updating the gist taking that into account. ;-)

**Comment by donmelton** [comment]
@JMoVS I didn't actually merge this because I didn't like the wording or formatting. :) So I rewrote the whole thing and checked it in as commit https://github.com/donmelton/video_transcoding/commit/9fd4b8ef4e0e3959e1d1d1a339aa7c9c3ac6c472.

But I'll still reference this pull request in the release notes later.

Thanks again!

**Comment by JMoVS** [comment]
@donmelton  jebus, you did put that in a hell of a more prominent spot than my original suggestion. Wow. Thank you! Very curious to see the responses. And thank you for the PR reference ;-)

**Pull request closed without merging**
