### PR TITLE
Fix veryfast preset of handbrakeCLI nightly

### PR DESCRIPTION
**Pull request by cnrd**
As we just discussed.

Force handbrakeCLI to use medium preset

### CODE REVIEW

**Comment by donmelton** [comment]
@cnrd I'll consider but first I want to find out what kind of crack the HandBrake development team has been smoking to make `veryfast` the default.

In the meantime, when using nightly builds, add `-H encoder-preset=medium` to your command line to get the default behavior.

**Comment by cnrd** [comment]
Will do!

Thanks :-)

**Comment by donmelton** [comment]
@cnrd OK, it looks like the change to `veryfast` as the default preset is intentional by the HandBrake development team, however misguided. And it looks like they've changed other defaults. Which means the fix I have to make will likely be more than just the preset.

Stay tuned.

**Comment by donmelton** [comment]
@cnrd OK, I took your patch. Thanks.

But I had to fix your spacing (none before commas, please) and rewrap your line. Just be careful with that the next time.

Looks like I won't have to change anything else. But I'll test this for awhile before I release it.

**Comment by cnrd** [comment]
Yeah I see that, sorry that was sloppy coding... I totally agree on only having spaces after a comma. Thanks for fixing it up.

Will be more careful if I propose other patches.

**Comment by donmelton** [comment]
@cnrd No worries, man. Keep the patches coming. :)

**Comment by donmelton** [comment]
@cnrd BTW, are you on Twitter? What's your account name so I can keep an eye on you? :)

**Comment by cnrd** [comment]
I'm @ConradAndersen on Twitter, not that I really write much on there, mostly use it as a newsfeed :-)

**Comment by donmelton** [comment]
@cnrd Ah! I thought that might be you. :)

BTW, I spent the day following up on your fix in a big way. Lots of changes to support HandBrake nightlies. There was far more wrong than I thought. So, I just released version 0.3.1.

**Pull request merged**
