### PR TITLE
Add Docker instructions to README

### PR DESCRIPTION
**Pull request by ntodd**
Docker instructions added above Linux and Windows as it may prove a better way to use on those systems.  I can put the info in a gist or just use a link to the docker image page if you want to simplify.

### CODE REVIEW

**Comment by donmelton** [comment]
@ntodd Thanks for submitting a patch!

But I'm not going to take this as is. Here's why...

First, you're making several changes to the README that have nothing to do with documenting Docker support. Apparently these changes are some kind of line ending horkage. You need to fix those.

Second, your Docker-specific addition is way too long. I expect only a few of my users will ever leverage Docker, so I just want a single link to your page where the command line instructions are given.

Thanks.

**Comment by ntodd** [comment]
Sorry, my editor cleans up whitespace automatically on save.  Didn't catch it.

**Comment by donmelton** [comment]
@ntodd OK, I plan to add a link to your page in the README this week when I put out a new release. However, I've rewritten your text like this:

If you're comfortable using [Docker virtualization software](https://en.wikipedia.org/wiki/Docker_(software)), then a pre-built container with everything you need, plus installation instructions, is available here:

<https://hub.docker.com/r/ntodd/video-transcoding/>

**Comment by donmelton** [comment]
@ntodd OK, I've added Docker virtualization software installation instructions to the "README" document for version 0.12.3 which I just released. I didn't use your patch since I completely reworded the text.

Thanks again for making the original enhancement request!

**Pull request closed without merging**
